[build-system]
requires = ['setuptools>=80', 'setuptools-scm[simple]>=10']
build-backend = 'setuptools.build_meta'

[project]
name = 'pyorbs'
description = 'A tool for managing Python virtual environments'
readme = 'README.rst'
requires-python = '~= 3.12'
license = 'MIT'
authors = [{name = 'Logikal GmbH', email = 'contact@logikal.io'}]
keywords = ['development', 'virtual environment']
classifiers = [
  'Development Status :: 5 - Production/Stable',
  'Intended Audience :: Developers',
  'Operating System :: POSIX :: Linux',
  'Programming Language :: Python :: 3',
  'Programming Language :: Python :: 3.12',
  'Environment :: Console',
  'Topic :: Software Development',
  'Topic :: Utilities',
  'Typing :: Typed',
]
dynamic = ['version']

[project.scripts]
orb = 'pyorbs.orb:main'

[project.urls]
'Documentation' = 'https://docs.logikal.io/pyorbs/'
'Release notes' = 'https://github.com/logikal-io/pyorbs/releases'
'Issue tracker' = 'https://github.com/logikal-io/pyorbs/issues'
'Source code' = 'https://github.com/logikal-io/pyorbs'

[tool.setuptools]
packages = ['pyorbs', 'pyorbs.templates']

[tool.coverage.run]
patch = ['subprocess']
