name: Publish release
on:
  release:
    types: [released]

jobs:
  publish-release:
    name: Publish release
    uses: logikal-io/github-workflows/.github/workflows/publish-release.yml@v5
    with:
      name: pyorbs
    permissions:
      contents: read
      id-token: write
    secrets: inherit
