name: Test pull request
on: pull_request

jobs:
  run-python-tests:
    name: Run Python tests
    uses: logikal-io/github-workflows/.github/workflows/run-python-tests.yml@v4
    with:
      init-commands: sudo apt-get install fish
      fetch-depth: 0  # needed for inferring the correct editable install version
    permissions:
      contents: read
      id-token: write
    secrets: inherit
