name: Test pull request
on: pull_request

jobs:
  run-python-tests:
    name: Run Python tests
    uses: logikal-io/github-workflows/.github/workflows/run-python-tests.yml@v5
    with:
      fetch-depth: 0  # needed for inferring the correct editable install version
      playbook-roles: fish
      upload-artifacts: false
    permissions:
      contents: read
      id-token: write
    secrets: inherit
